const users = [
    {
      username: "jsmith",
      password: "password123",
      email: "jsmith@example.com",
      firstName: "John",
      lastName: "Smith",
    },
    {
      username: "mjordan",
      password: "hoopstar23",
      email: "mjordan@example.com",
      firstName: "Michael",
      lastName: "Jordan",
    },
    {
      username: "@ada",
      password: "analyticalEng",
      email: "alovelace@example.com",
      firstName: "Ada",
      lastName: "Lovelace",
    },
    {
      username: "turing42",
      password: "enigmaMachine",
      email: "aturing@example.com",
      firstName: "Alan",
      lastName: "Turing",
    },
    {
      username: "granger_h",
      password: "leviosa99",
      email: "grangerh@example.com",
      firstName: "Hermione",
      lastName: "Granger",
    },
    {
      username: "einstein_al",
      password: "e=mc2",
      email: "einstein@example.com",
      firstName: "Albert",
      lastName: "Einstein",
    },
    {
      username: "tesla_n",
      password: "acdc123",
      email: "teslan@example.com",
      firstName: "Nikola",
      lastName: "Tesla",
    },
    {
      username: "curie_m",
      password: "radium88",
      email: "curiem@example.com",
      firstName: "Marie",
      lastName: "Curie",
    },
    {
      username: "knight_b",
      password: "darkKnight",
      email: "bruce@example.com",
      firstName: "Bruce",
      lastName: "Wayne",
    },
    {
      username: "stark_t",
      password: "ironman3000",
      email: "tonystark@example.com",
      firstName: "Tony",
      lastName: "Stark",
    },
    {
      username: "wayne_g",
      password: "hockey99",
      email: "gwayne@example.com",
      firstName: "Wayne",
      lastName: "Gretzky",
    },
    {
      username: "bond_j",
      password: "007agent",
      email: "jamesbond@example.com",
      firstName: "James",
      lastName: "Bond",
    },
    {
      username: "yoda_m",
      password: "forceStrong",
      email: "yoda@example.com",
      firstName: "Master",
      lastName: "Yoda",
    },
    {
      username: "potter_h",
      password: "quidditch123",
      email: "hpotter@example.com",
      firstName: "Harry",
      lastName: "Potter",
    },
    {
      username: "skywalker_l",
      password: "jediMaster",
      email: "lukeskywalker@example.com",
      firstName: "Luke",
      lastName: "Skywalker",
    },
  ];

  const users2 = [
    {
      username: "ade_boss",
      password: "naijaKing",
      email: "adewale@example.com",
      firstName: "Adewale",
      lastName: "Ogunleye",
    },
    {
      username: "chioma_q",
      password: "queenChi",
      email: "chioma@example.com",
      firstName: "Chioma",
      lastName: "Okonkwo",
    },
    {
      username: "tunde_xo",
      password: "babaTunde123",
      email: "tunde@example.com",
      firstName: "Tunde",
      lastName: "Balogun",
    },
    {
      username: "zubby_don",
      password: "Zubby2024",
      email: "zubby@gmail.com",
      firstName: "Zubairu",
      lastName: "Nwankwo",
    },
    {
      username: "yemi_cool",
      password: "yemiLagos",
      email: "yemi@example.com",
      firstName: "Yemi",
      lastName: "Adesanya",
    },
    {
      username: "faithy_p",
      password: "GodIsGreat",
      email: "faith@example.com",
      firstName: "Faith",
      lastName: "Eze",
    },
    {
      username: "olamide_rock",
      password: "badooBoss",
      email: "olamide@example.com",
      firstName: "Olamide",
      lastName: "Olowo",
    },
    {
      username: "bello_hustle",
      password: "hustleHard",
      email: "bello@example.com",
      firstName: "Bello",
      lastName: "Musa",
    },
    {
      username: "tosin_vibes",
      password: "tosin123",
      email: "tosin@example.com",
      firstName: "Tosin",
      lastName: "Adeyemi",
    },
    {
      username: "ife_star",
      password: "ifeLove",
      email: "ife@example.com",
      firstName: "Ifeoma",
      lastName: "Okafor",
    },
    {
      username: "emma_fresh",
      password: "emmaJaga",
      email: "emma@example.com",
      firstName: "Emmanuel",
      lastName: "Uche",
    },
    {
      username: "amaka_wow",
      password: "AmakaRules",
      email: "amaka@example.com",
      firstName: "Amaka",
      lastName: "Obi",
    },
    {
      username: "segun_coder",
      password: "devSegun",
      email: "segun@example.com",
      firstName: "Segun",
      lastName: "Adebayo",
    },
    {
      username: "halima_g",
      password: "HalimaGold",
      email: "halima@gmail.com",
      firstName: "Halima",
      lastName: "Bello",
    },
    {
      username: "uche_money",
      password: "ucheEgo",
      email: "uche@example.com",
      firstName: "Uche",
      lastName: "Nnaji",
    },
  ];
  

  //pasword: abc12345
  console.log(users);
  