const users = [
    {
      username: "jsmith",
      password: "password123",
      email: "jsmith@example.com",
      firstName: "John",
      lastName: "Smith",
    },
    {
      username: "mjordan",
      password: "hoopstar23",
      email: "mjordan@example.com",
      firstName: "Michael",
      lastName: "Jordan",
    },
    {
      username: "@ada",
      password: "ANALYTICALENG",
      email: "alovelace@example.com",
      firstName: "Ada",
      lastName: "Lovelace",
    },
    {
      username: "turing42",
      password: "enigmaMachine",
      email: "aturing@example.com",
      firstName: "Alan",
      lastName: "Turing",
    },
    {
      username: "granger_h",
      password: "leviosa99",
      email: "grangerh@example.com",
      firstName: "Hermione",
      lastName: "Granger",
    },
    {
      username: "einstein_al",
      password: "e=mc2",
      email: "einstein@example.com",
      firstName: "Albert",
      lastName: "Einstein",
    },
    {
      username: "tesla_n",
      password: "acdc123",
      email: "teslan@example.com",
      firstName: "Nikola",
      lastName: "Tesla",
    },
    {
      username: "curie_m",
      password: "radium88",
      email: "curiem@example.com",
      firstName: "Marie",
      lastName: "Curie",
    },
    {
      username: "knight_b",
      password: "darkKnight",
      email: "bruce@example.com",
      firstName: "Bruce",
      lastName: "Wayne",
    },
    {
      username: "stark_t",
      password: "ironman3000",
      email: "tonystark@example.com",
      firstName: "Tony",
      lastName: "Stark",
    },
    {
      username: "wayne_g",
      password: "hockey99",
      email: "gwayne@example.com",
      firstName: "Wayne",
      lastName: "Gretzky",
    },
    {
      username: "bond_j",
      password: "007agent",
      email: "jamesbond@example.com",
      firstName: "James",
      lastName: "Bond",
    },
    {
      username: "yoda_m",
      password: "forceStrong",
      email: "yoda@example.com",
      firstName: "Master",
      lastName: "Yoda",
    },
    {
      username: "potter_h",
      password: "quidditch123",
      email: "hpotter@example.com",
      firstName: "Harry",
      lastName: "Potter",
    },
    {
      username: "skywalker_l",
      password: "jediMaster",
      email: "lukeskywalker@example.com",
      firstName: "Luke",
      lastName: "Skywalker",
    },
  ];
