import type { Metadata } from "next";
import { Cormorant, Geist } from "next/font/google";
import { ViewTransitions } from "next-view-transitions";
import { Toaster } from "sonner";
import { interVar } from "@/lib/font";
import { ThemeProvider } from "../components/theme-provider";
import "./globals.css";

const cormorant = Cormorant({
  variable: "--font-cormorant",
  subsets: ["latin"],
});

export const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html
        lang="en"
        className={`${interVar.className} ${cormorant.variable} ${geistSans.variable} antialiased`}
        suppressHydrationWarning
      >
        <body className="text-zinc-900 dark:text-white bg-white dark:bg-[var(--background)]">
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            disableTransitionOnChange
            enableSystem
          >
            <main>
              {children}
              <Toaster />
            </main>
          </ThemeProvider>
        </body>
      </html>
    </ViewTransitions>
  );
}
